In [1]:
import numpy as np
import pandas as pd

#                                    # Analysis Data wrangling with Numpy

In [2]:
np.array([5,9,13])

array([ 5,  9, 13])

In [3]:
type([5,9,13])

list

In [5]:
# Two Dimention 
a=np.array([[1,2],[3,4],[4,5]])
print("Type-",a.dtype)
print('\n','-'*30)
print('\n',a)

Type- int32

 ------------------------------

 [[1 2]
 [3 4]
 [4 5]]


In [6]:
#dtype conversion
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

# Numpy Data Types

In [11]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(type(mat))

<class 'numpy.ndarray'>


In [14]:
print("Here is the matrix  \n--------------\n",mat,"\n--------------")
print("dimention  of this metrix :",mat.ndim,sep="")
print("shape of this matrix :",mat.shape)
print("data type of this matrix :",mat.dtype)

Here is the matrix  
--------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------------
dimention  of this metrix :2
shape of this matrix : (3, 3)
data type of this matrix : int32


# Numpy arange Linspace

In [15]:
# dont work with python range
list=(range(2,10.5,4))
list # it will not work

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
a=np.arange(2,10.5,4)
a

array([ 2.,  6., 10.])

In [17]:
# reverse order
a[::-1]

array([10.,  6.,  2.])

In [18]:
print(" Every 5th nu. from 50 in reverse order \n",np.arange(50,0,-5))

 Every 5th nu. from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5]


In [19]:
print("Linearly spaced number between 1 & 5 \n------------------------")
print(np.linspace(10,40,5))

Linearly spaced number between 1 & 5 
------------------------
[10.  17.5 25.  32.5 40. ]


In [20]:
# include end point and check space between the point 
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

# matrix Creation

In [21]:
print("Venctor of Zeros \n--------------------")
print(np.zeros(5))

Venctor of Zeros 
--------------------
[0. 0. 0. 0. 0.]


In [22]:
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Numpy matrix Reshape

In [23]:
print("vector of zeros \n----------------------")
print(np.zeros(5))

vector of zeros 
----------------------
[0. 0. 0. 0. 0.]


In [24]:
print("matrix of zeros \n ------------------")
print(np.zeros((5,6))) # noticed tuple

matrix of zeros 
 ------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
print("matrix of ones \n--------------------")
print(np.ones((5,8)))

matrix of ones 
--------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
print("matrix of 5 \n----------------------")
print(5*np.ones((2,3)))

matrix of 5 
----------------------
[[5. 5. 5.]
 [5. 5. 5.]]


In [27]:
# construct diagonal matrix
n= np.arange(30).reshape(3,10)
print(n)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


# Random Number

In [30]:
np.random.seed(5)
print(" Random number generation(from uniform distribution)")
print(np.random.rand(10,6))
print("Number from normal dist.with zeros means & standard deviation 1 i.e std normal")

 Random number generation(from uniform distribution)
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]
Number from normal dist.with zeros means & standard deviation 1 i.e std normal


In [32]:
print(np.random.randn(10,3))

[[ 1.18906073 -0.07359332 -2.85968797]
 [ 0.7893664  -1.87774088  1.53875615]
 [ 1.82136474 -0.42703139 -1.16470191]
 [-1.39707402  0.87265462 -0.20211818]
 [-0.59835993 -0.2434197   2.08851469]
 [ 0.34691933  0.74572695  0.77690759]
 [ 1.01842113  1.06135144 -0.71046645]
 [-0.2151878  -0.76076031 -0.71116323]
 [ 1.14150774 -0.50175555 -0.07915136]
 [-0.69282634 -0.59340277  0.78823794]]


In [34]:
print("random integers matrix")
print(np.random.randint(1,30,(6,7)))
# randint (low.high. no. of sample to be drawn in a tuple to form a matrix)

random integers matrix
[[29 24  6  2 28  7 28]
 [ 8  4 15 10  8 26 27]
 [ 8 23  7 15  5 11 22]
 [11  5  1 17 18 29  6]
 [ 4 16 18 24 17 12 27]
 [26  9 20 21 21 11 26]]


# Numpy conditions

In [35]:
a=np.random.randint(1,40,10)
a

array([10, 32, 23, 17, 16, 16, 32, 14, 18, 36])

In [36]:
#replace data with fixed number
np.clip(a,a_min=10,a_max=250) # clip method use for fix replace data

array([10, 32, 23, 17, 16, 16, 32, 14, 18, 36])

In [40]:
print(np.where(a<10))

(array([], dtype=int64),)


In [41]:
# find if data exist in the array
print(np.where(a==38))

(array([], dtype=int64),)


# Reshape And sorting

In [3]:
from numpy.random import randint as ri

In [4]:
a=ri(1,99,30)
a

array([94, 93, 14, 41, 97, 91,  6,  1, 96, 88, 64, 39, 27, 69, 16, 53, 85,
       94, 91, 61, 47, 35, 40, 35, 77, 23, 29, 96, 87, 92])

In [5]:
b=a.reshape(2,3,5) # two matrix,3 rows 5 columns
b

array([[[94, 93, 14, 41, 97],
        [91,  6,  1, 96, 88],
        [64, 39, 27, 69, 16]],

       [[53, 85, 94, 91, 61],
        [47, 35, 40, 35, 77],
        [23, 29, 96, 87, 92]]])

In [6]:
c=a.reshape(6,5)
c

array([[94, 93, 14, 41, 97],
       [91,  6,  1, 96, 88],
       [64, 39, 27, 69, 16],
       [53, 85, 94, 91, 61],
       [47, 35, 40, 35, 77],
       [23, 29, 96, 87, 92]])

In [8]:
print("min of a :",c.min())
print("max of a :",c.max())

min of a : 1
max of a : 97


# Sorting

In [9]:
M=ri(1,100,25).reshape(5,5)
#matrix of random integers

In [10]:
print("\n 5*5 matrix of random integers\n",'-'*50,'\n',M)


 5*5 matrix of random integers
 -------------------------------------------------- 
 [[ 1  9 15 24  8]
 [42 31 60  7  7]
 [24 28 77 43 29]
 [26 14 50 32 82]
 [19 86 79 53 95]]


In [11]:
print("\n here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(M)) # default axis=1


 here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[ 1  8  9 15 24]
 [ 7  7 31 42 60]
 [24 28 29 43 77]
 [14 26 32 50 82]
 [19 53 79 86 95]]


In [13]:
print('\n here is the sorted matrix along each column \n','-'*50,'\n',np.sort(M,axis=0))


 here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[ 1  9 15  7  7]
 [19 14 50 24  8]
 [24 28 60 32 29]
 [26 31 77 43 82]
 [42 86 79 53 95]]


# Indexing sort and Update

In [14]:
arr=np.arange(13,30)
print("array:",arr)

array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [15]:
print("Element at 7th index is :",arr[7])

Element at 7th index is : 20


In [ ]:
print("elements from 3rd to 5th index are:",arr[3:6])

In [17]:
print("elements up to 4th  index are:",arr[4:])
abc=arr[4:]
abc

elements up to 4th  index are: [17 18 19 20 21 22 23 24 25 26 27 28 29]


array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
print("Elemts from last backwards are:",arr[-1::-2])

Elemts from last backwards are: [29 27 25 23 21 19 17 15 13]


In [19]:
print("7 Elements from last backwards are:",arr[-1:-8:-1])

7 Elements from last backwards are: [29 28 27 26 25 24 23]


In [20]:
arr=np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [21]:
print("Elements at 2nd ,4th and 9th index are :",arr[[2,4,9]])

Elements at 2nd ,4th and 9th index are : [ 4  8 18]


In [22]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print("\n Double bracket indexing \n----------------------")
print("Elements in row index 1 & column index 2:",mat[1][2])


 Double bracket indexing 
----------------------
Elements in row index 1 & column index 2: 6


In [25]:
print("entire raw at index 2:",mat[2])
print("\n Entire column at index 3:\n",mat[:,1:])

entire raw at index 2: [7 8 9]

 Entire column at index 3:
 [[2 3]
 [5 6]
 [8 9]]


In [26]:
print("\n subsetting sub-matrics\n-----------------")
print("matrix with row index 1& 2 and column index 3 & 4 \n",mat[1:2,1:2])


 subsetting sub-matrics
-----------------
matrix with row index 1& 2 and column index 3 & 4 
 [[5]]


In [27]:
print(mat[0:2,[1,2]]) # raw and column

[[2 3]
 [5 6]]


# update matrix

In [28]:
print('Original matrix \n',mat)

Original matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
mat[0,1]=35
print(mat)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


# Subsetting

In [30]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("matrix of random 2 digit number \n---------------------------------\n",mat)

matrix of random 2 digit number 
---------------------------------
 [[22 96 15 97 87]
 [37 39 89 25 26]
 [47 85 67 35 95]]


In [31]:
xyz=mat[mat>70]
xyz

array([96, 97, 87, 89, 85, 95])

In [32]:
print("elements geater than 50 \n",mat[mat>50])

elements geater than 50 
 [96 97 87 89 85 67 95]


In [33]:
mat>50 #it will shown True or false 

array([[False,  True, False,  True,  True],
       [False, False,  True, False, False],
       [False,  True,  True, False,  True]])

In [34]:
print(np.where(mat==55))

(array([], dtype=int64), array([], dtype=int64))


# Universal function

In [35]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

In [36]:
print("\n 1st matrix of random single digit number \n---------------------------------------------\n",mat1)
print("\n 2nd matrix of random single digit number \n---------------------------------------------\n",mat2)


 1st matrix of random single digit number 
---------------------------------------------
 [[7 6 9]
 [9 5 9]
 [4 9 9]]

 2nd matrix of random single digit number 
---------------------------------------------
 [[5 5 4]
 [3 9 7]
 [7 6 9]]


In [37]:
print("\n Addition \n-------------------------------------------\n",mat1+mat2)
print("\n Multiplication \n-------------------------------------------\n",mat1*mat2)


 Addition 
-------------------------------------------
 [[12 11 13]
 [12 14 16]
 [11 15 18]]

 Multiplication 
-------------------------------------------
 [[35 30 36]
 [27 45 63]
 [28 54 81]]


In [38]:
print("mat1 \n",mat1)
print("mat1 \n",mat2)

mat1 
 [[7 6 9]
 [9 5 9]
 [4 9 9]]
mat1 
 [[5 5 4]
 [3 9 7]
 [7 6 9]]


In [39]:
print("\n Division \n-------------------------------------------\n",mat1/mat2)
print("\n Linear Combination =3*A - 2*A \n-----------------------------------\n",3*mat1-2*mat2)


 Division 
-------------------------------------------
 [[1.4        1.2        2.25      ]
 [3.         0.55555556 1.28571429]
 [0.57142857 1.5        1.        ]]

 Linear Combination =3*A - 2*A 
-----------------------------------
 [[11  8 19]
 [21 -3 13]
 [-2 15  9]]


# BroadCasting

In [40]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [43]:
start=np.zeros((3,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
y=start+add_rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [45]:
new_rows=add_rows.T
new_rows

array([[1],
       [0],
       [2]])

In [46]:
text=new_rows+start
print(text)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


In [47]:
#create an array which is 4*1 to broadcaste across columns
add_col=np.array([[0,1,2,3]])
add_cols=add_col.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


# Array Math

In [48]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

In [50]:
print(mat1)
print('\n',mat2)

[[5 8 1]
 [7 4 3]
 [9 9 5]]

 [[7 9 5]
 [7 5 6]
 [8 2 6]]


In [51]:
print("\n sq-root of 1st matrix using np \n---------------------------------------\n",np.sqrt(mat1))


 sq-root of 1st matrix using np 
---------------------------------------
 [[2.23606798 2.82842712 1.        ]
 [2.64575131 2.         1.73205081]
 [3.         3.         2.23606798]]


In [52]:
print("\n square of 1st matrix using np \n---------------------------------------\n",np.square(mat1))


 square of 1st matrix using np 
---------------------------------------
 [[25 64  1]
 [49 16  9]
 [81 81 25]]


In [53]:
import numpy
print(dir(numpy))


# All function of numpy

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

#                                  # Analysis Data wrangling with Pandas

In [2]:
ser = pd.Series()
ser

Series([], dtype: object)

In [3]:
ser=pd.Series([0,10,20,30,40,50,60,70,80,90])
ser

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64

In [4]:
#Notice datatype
ser=pd.Series([20,15.7,'10']) # it is updated series
ser

0      20
1    15.7
2      10
dtype: object

In [5]:
#create dictionary
dict={'A':[1,2,5],'B':[5,8,9],'C':[1,2,3]}
df=pd.DataFrame(dict)
df

A  B  C
0  1  5  1
1  2  8  2
2  5  9  3

In [6]:
#add new column and add new value into it
df["State"]="CA NV AZ".split() # where the space it will break data with the help of split method
df

A  B  C State
0  1  5  1    CA
1  2  8  2    NV
2  5  9  3    AZ

In [7]:
#now we create nan values and its manipulated
dict={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
dict

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [8]:
df=pd.DataFrame(dict)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [9]:
df['D']=[20,30,40] # new column add like this
df

A    B  C   D
0  1.0  5.0  1  20
1  2.0  NaN  2  30
2  NaN  NaN  3  40

In [10]:
print("\Dropping any column with nan value \n",'-'*35,sep='')
print(df.dropna(axis=1)) # remove nan values column wise

\Dropping any column with nan value 
-----------------------------------
   C   D
0  1  20
1  2  30
2  3  40


In [11]:
print("\Dropping any row with nan value \n",'-'*35,sep='')
print(df.dropna(axis=0)) # remove nan values row wise

\Dropping any row with nan value 
-----------------------------------
     A    B  C   D
0  1.0  5.0  1  20


In [12]:
print("\n filling value with a default value",'-'*35,sep='')
print(df.fillna(value=50))


 filling value with a default value-----------------------------------
      A     B  C   D
0   1.0   5.0  1  20
1   2.0  50.0  2  30
2  50.0  50.0  3  40


In [13]:
print("\n filling value with a computed value (mean of column A here)\n",'-'*60,sep='')
print(df.fillna(value=df['C'].mean(),inplace=True)) # save data permanently
df


 filling value with a computed value (mean of column A here)
------------------------------------------------------------
None


A    B  C   D
0  1.0  5.0  1  20
1  2.0  2.0  2  30
2  2.0  2.0  3  40

# Group By

In [14]:
#create dictionary
data={'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
     'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
     'Sale':[200,120,340,124,243,350]}
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sale': [200, 120, 340, 124, 243, 350]}

In [15]:
df=pd.DataFrame(data)
df

Company   Person  Sale
0    GOOG      Sam   200
1    GOOG  Charlie   120
2    MSFT      Amy   340
3    MSFT  Vanessa   124
4      FB     Carl   243
5      FB    Sarah   350

In [16]:
# Making groups
bycomp=df.groupby('Company')
print("\n Grouping by company column & listing mean sales \n",'-'*55,sep='')
print(bycomp.mean(numeric_only=True))
#print(bycomp['sale'].mean())


 Grouping by company column & listing mean sales 
-------------------------------------------------------
          Sale
Company       
FB       296.5
GOOG     160.0
MSFT     232.0


In [17]:
print("\n Grouping by company column & listing sum of sales \n",'-'*55,sep='')
print(bycomp.sum(numeric_only=True))


 Grouping by company column & listing sum of sales 
-------------------------------------------------------
         Sale
Company      
FB        593
GOOG      320
MSFT      464


# Concate Merge Join

In [18]:
#create dataframe
df1=pd.DataFrame({
    'Mat':[40,64,55,45],
    'Eng':[56,87,34,56],
    'Sci':[56,67,89,71],
    'Chem':[44,59,98,56],
},index=['Ravi','Syam','Farhad','Abhi'])
df1

Mat  Eng  Sci  Chem
Ravi     40   56   56    44
Syam     64   87   67    59
Farhad   55   34   89    98
Abhi     45   56   71    56

In [19]:
df2=pd.DataFrame({
    'Mat':[50,77,95,74],
    'Eng':[66,87,34,66],
    'Sci':[81,87,69,71],
    'Chem':[56,79,12,34]},index=['Shan','Mahi','Viru','Mona'])
df2

Mat  Eng  Sci  Chem
Shan   50   66   81    56
Mahi   77   87   87    79
Viru   95   34   69    12
Mona   74   66   71    34

In [20]:
df3=pd.DataFrame({
    'Mat':[67,89,98,56],
    'Eng':[56,87,89,71],
    'Sci':[56,67,56,87],
    'Chem':[34,56,56,87]},index=['Astha','Rohit','Rohil','Shital'])
df3

Mat  Eng  Sci  Chem
Astha    67   56   56    34
Rohit    89   87   67    56
Rohil    98   89   56    56
Shital   56   71   87    87

In [21]:
#concatenation
df_cat1=pd.concat([df1,df2,df3],axis=0)
print("\n after concatenation along row \n",'-'*30,sep='')
print(df_cat1)


 after concatenation along row 
------------------------------
        Mat  Eng  Sci  Chem
Ravi     40   56   56    44
Syam     64   87   67    59
Farhad   55   34   89    98
Abhi     45   56   71    56
Shan     50   66   81    56
Mahi     77   87   87    79
Viru     95   34   69    12
Mona     74   66   71    34
Astha    67   56   56    34
Rohit    89   87   67    56
Rohil    98   89   56    56
Shital   56   71   87    87


In [22]:
#concatenation
df_cat2=pd.concat([df1,df2,df3],axis=1)
print("\n after concatenation along columns \n",'-'*30,sep='')
print(df_cat2)


 after concatenation along columns 
------------------------------
         Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem
Ravi    40.0  56.0  56.0  44.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Syam    64.0  87.0  67.0  59.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Farhad  55.0  34.0  89.0  98.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Abhi    45.0  56.0  71.0  56.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Shan     NaN   NaN   NaN   NaN  50.0  66.0  81.0  56.0   NaN   NaN   NaN   NaN
Mahi     NaN   NaN   NaN   NaN  77.0  87.0  87.0  79.0   NaN   NaN   NaN   NaN
Viru     NaN   NaN   NaN   NaN  95.0  34.0  69.0  12.0   NaN   NaN   NaN   NaN
Mona     NaN   NaN   NaN   NaN  74.0  66.0  71.0  34.0   NaN   NaN   NaN   NaN
Astha    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  67.0  56.0  56.0  34.0
Rohit    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  89.0  87.0  67.0  56.0
Rohil    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  98.0  8

In [23]:
#fill here null values
df_cat2.fillna(value=0,inplace=True)
df_cat2

Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem
Ravi    40.0  56.0  56.0  44.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Syam    64.0  87.0  67.0  59.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Farhad  55.0  34.0  89.0  98.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Abhi    45.0  56.0  71.0  56.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Shan     0.0   0.0   0.0   0.0  50.0  66.0  81.0  56.0   0.0   0.0   0.0   0.0
Mahi     0.0   0.0   0.0   0.0  77.0  87.0  87.0  79.0   0.0   0.0   0.0   0.0
Viru     0.0   0.0   0.0   0.0  95.0  34.0  69.0  12.0   0.0   0.0   0.0   0.0
Mona     0.0   0.0   0.0   0.0  74.0  66.0  71.0  34.0   0.0   0.0   0.0   0.0
Astha    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  67.0  56.0  56.0  34.0
Rohit    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  89.0  87.0  67.0  56.0
Rohil    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  98.0  89.0  56.0  56.0
Shital   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  56.0  71.0  87.0  87.0

In [24]:
# Merging by common keys
left=pd.DataFrame({
    'key':['K0','K1','K2','K5'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
})
Right=pd.DataFrame({
    'key':['K0','K1','K2','K3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3'],
})

In [25]:
print("\n the dataframe 'Left' \n",'-'*30,sep='')
print(left)


 the dataframe 'Left' 
------------------------------
  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K5  A3  B3


In [26]:
print("\n the dataframe 'Right' \n",'-'*30,sep='')
print(Right)


 the dataframe 'Right' 
------------------------------
  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3


# Merge Data

In [27]:
merge1=pd.merge(left,Right,how='inner',on='key')
print("\n  after simple merging with inner method \n",'-'*30,sep='')
print(merge1)


#here which is match keys that is merge by merge method
#on the key basis we maerge key which is common here
#inner means data match it display
#if we not write how pera meter it will take defult


  after simple merging with inner method 
------------------------------
  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2


In [28]:
left=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2']},index=['K0','K1','K2'])
right=pd.DataFrame({
    'C':['C0','C2','C3'],
    'D':['D0','D2','D3']},index=['K0','K2','K3'])

In [29]:
left.join(right)
#left data not change will remain same right data adjust with left

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [31]:
left.join(right,how='outer')
#all both table data will be displayed if we use outer
#if we want show all data then use how perameter

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

# Data Manipulation

In [32]:
# define a function
def salary_hike(x):
    if(x>3000):
        return np.ceil(x+(x*.30))
    else:
        return np.ceil(x*1.5)

In [116]:
df=pd.DataFrame({'Dept':[1,2,3,4,5,6,7,8,9,10],
                'Emp_Name':['Rajesh','Shankar','Sindhu','Akshay','Vivan','Monika','Salman','Aisha','Remo','Amit'],
                'Salary':[4944,5455,6166,4044,3433,2922,6466,7977,6766,5155]})
df

Dept Emp_Name  Salary
0     1   Rajesh    4944
1     2  Shankar    5455
2     3   Sindhu    6166
3     4   Akshay    4044
4     5    Vivan    3433
5     6   Monika    2922
6     7   Salman    6466
7     8    Aisha    7977
8     9     Remo    6766
9    10     Amit    5155

In [117]:
df['New_salary']=df['Salary'].apply(salary_hike)
print(df)

   Dept Emp_Name  Salary  New_salary
0     1   Rajesh    4944      6428.0
1     2  Shankar    5455      7092.0
2     3   Sindhu    6166      8016.0
3     4   Akshay    4044      5258.0
4     5    Vivan    3433      4463.0
5     6   Monika    2922      4383.0
6     7   Salman    6466      8406.0
7     8    Aisha    7977     10371.0
8     9     Remo    6766      8796.0
9    10     Amit    5155      6702.0


In [120]:
df['Name_length']=df['Emp_Name'].apply(len)
print(df)

   Dept Emp_Name  Salary  New_salary  Name_length
0     1   Rajesh    4944      6428.0            6
1     2  Shankar    5455      7092.0            7
2     3   Sindhu    6166      8016.0            6
3     4   Akshay    4044      5258.0            6
4     5    Vivan    3433      4463.0            5
5     6   Monika    2922      4383.0            6
6     7   Salman    6466      8406.0            6
7     8    Aisha    7977     10371.0            5
8     9     Remo    6766      8796.0            4
9    10     Amit    5155      6702.0            4


In [121]:
df['New_salary'].apply(lambda x : np.sqrt(x))

0     80.174809
1     84.214013
2     89.532117
3     72.512068
4     66.805688
5     66.204229
6     91.684241
7    101.838107
8     93.786993
9     81.865744
Name: New_salary, dtype: float64

In [126]:
print("\n sum of the column 'New salary' is :",df['New_salary'].sum())


 sum of the column 'New salary' is : 69915.0


In [130]:
print(" min and max of the column 'New Salary' is:",df['New_salary'].min(),'&',df['New_salary'].max())

 min and max of the column 'New Salary' is: 4383.0 & 10371.0


In [131]:
# Deletion sorting list of the column
print("\n Name of clomun \n",'-'*20,sep='')
print(df.columns)


 Name of clomun 
--------------------
Index(['Dept', 'Emp_Name', 'Salary', 'New_salary', 'Name_length'], dtype='object')


In [132]:
l=list(df.columns)
print("\n columns name in a list of string for later manipulation:",l)


 columns name in a list of string for later manipulation: ['Dept', 'Emp_Name', 'Salary', 'New_salary', 'Name_length']


In [133]:
print("\n Deleting column by 'del' command \n",'-'*50,sep='')
del df['Salary']
print(df)


 Deleting column by 'del' command 
--------------------------------------------------
   Dept Emp_Name  New_salary  Name_length
0     1   Rajesh      6428.0            6
1     2  Shankar      7092.0            7
2     3   Sindhu      8016.0            6
3     4   Akshay      5258.0            6
4     5    Vivan      4463.0            5
5     6   Monika      4383.0            6
6     7   Salman      8406.0            6
7     8    Aisha     10371.0            5
8     9     Remo      8796.0            4
9    10     Amit      6702.0            4


In [134]:
df.sort_values(by='New_salary')

Dept Emp_Name  New_salary  Name_length
5     6   Monika      4383.0            6
4     5    Vivan      4463.0            5
3     4   Akshay      5258.0            6
0     1   Rajesh      6428.0            6
9    10     Amit      6702.0            4
1     2  Shankar      7092.0            7
2     3   Sindhu      8016.0            6
6     7   Salman      8406.0            6
8     9     Remo      8796.0            4
7     8    Aisha     10371.0            5

In [135]:
df.sort_values(by='New_salary',ascending=False)

Dept Emp_Name  New_salary  Name_length
7     8    Aisha     10371.0            5
8     9     Remo      8796.0            4
6     7   Salman      8406.0            6
2     3   Sindhu      8016.0            6
1     2  Shankar      7092.0            7
9    10     Amit      6702.0            4
0     1   Rajesh      6428.0            6
3     4   Akshay      5258.0            6
4     5    Vivan      4463.0            5
5     6   Monika      4383.0            6

In [ ]:
# finding all null values
df=pd.DataFrame

# Date time manipulation

In [33]:
date_range = pd.date_range('4/12/2021', periods=6)
dates=pd.DataFrame(date_range,columns=['Date'])
dates

Date
0 2021-04-12
1 2021-04-13
2 2021-04-14
3 2021-04-15
4 2021-04-16
5 2021-04-17

In [34]:
# if we want to show only month so one perameter frequency , freq='M'
date_range=pd.date_range('4/12/2021',periods=6,freq='M')
date_range

DatetimeIndex(['2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31',
               '2021-08-31', '2021-09-30'],
              dtype='datetime64[ns]', freq='M')

In [35]:
# we can take here 'Y',"D" freq ='Y' but d is here default.... create new column for seperate date
dates['Day']=dates['Date'].dt.day
dates['Month']=dates['Date'].dt.month
dates['Year']=dates['Date'].dt.year


In [36]:
dates

Date  Day  Month  Year
0 2021-04-12   12      4  2021
1 2021-04-13   13      4  2021
2 2021-04-14   14      4  2021
3 2021-04-15   15      4  2021
4 2021-04-16   16      4  2021
5 2021-04-17   17      4  2021

In [37]:
dates=pd.date_range('1/1/2000',periods=7)
ts=pd.Series(np.arange(7),index=dates)
print(ts)

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32


In [38]:
daterange=pd.date_range('2021/9/21',periods=6)
date=pd.DataFrame(date_range,columns=['Date'])
date

Date
0 2021-04-30
1 2021-05-31
2 2021-06-30
3 2021-07-31
4 2021-08-31
5 2021-09-30

In [39]:
# export your file where ever you want
ts.to_csv("........ give file name here")

# Data Cleaning

In [40]:
val1=np.array([1,np.nan,7,1,8])
val1

array([ 1., nan,  7.,  1.,  8.])

In [41]:
6+np.nan

nan

In [42]:
7*np.nan
# numpy does provide some special aggregation that will ignore those missing values

nan

In [43]:
np.nansum(val1)

17.0

In [44]:
# Nan and None in Pandas
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

# there are saveral methiod for removing and detecting replacing null, values in pandas data structure

isnull(): Generate a boolean mask indicatimng values notnull(): Opposite of isnull() dropna(): Return a filtered version of the data fillna(): Return a copy of the data with missing values filled or imputed.


In [45]:
# create dataFrame with missing values
raw_data={
    'First_name':['jason',np.nan,'Tina','jack',"Amy",'Madhu'],
    'Last_name':['Miller',np.nan,'Ali','Milers','coov','patil'],
    'Age':[42,np.nan,36,24,73,25],
    'Sex':['M',np.nan,'F','M','F','F'],
    'Unit1':[4,np.nan,np.nan,2,3,4],
    'Unit2':[3,np.nan,np.nan,4,4,4]}
df=pd.DataFrame(raw_data,columns=['First_name','Last_name','Age','Sex','Unit1','Unit2'])
df

First_name Last_name   Age  Sex  Unit1  Unit2
0      jason    Miller  42.0    M    4.0    3.0
1        NaN       NaN   NaN  NaN    NaN    NaN
2       Tina       Ali  36.0    F    NaN    NaN
3       jack    Milers  24.0    M    2.0    4.0
4        Amy      coov  73.0    F    3.0    4.0
5      Madhu     patil  25.0    F    4.0    4.0

In [46]:
df_no_missing=df.dropna()
df_no_missing # by this dropna method all null vales has removed

First_name Last_name   Age Sex  Unit1  Unit2
0      jason    Miller  42.0   M    4.0    3.0
3       jack    Milers  24.0   M    2.0    4.0
4        Amy      coov  73.0   F    3.0    4.0
5      Madhu     patil  25.0   F    4.0    4.0

In [47]:
# drop rows where all cells in that row in na
df

First_name Last_name   Age  Sex  Unit1  Unit2
0      jason    Miller  42.0    M    4.0    3.0
1        NaN       NaN   NaN  NaN    NaN    NaN
2       Tina       Ali  36.0    F    NaN    NaN
3       jack    Milers  24.0    M    2.0    4.0
4        Amy      coov  73.0    F    3.0    4.0
5      Madhu     patil  25.0    F    4.0    4.0

In [48]:
# rows that has all Nan's will be removed
df_cleaned=df.dropna(how='all')
df_cleaned
# here by use this how perameter we can removed all complete row which is null

First_name Last_name   Age Sex  Unit1  Unit2
0      jason    Miller  42.0   M    4.0    3.0
2       Tina       Ali  36.0   F    NaN    NaN
3       jack    Milers  24.0   M    2.0    4.0
4        Amy      coov  73.0   F    3.0    4.0
5      Madhu     patil  25.0   F    4.0    4.0

In [49]:
# create a new column full of missing values
df['Final_score']=np.nan
df

First_name Last_name   Age  Sex  Unit1  Unit2  Final_score
0      jason    Miller  42.0    M    4.0    3.0          NaN
1        NaN       NaN   NaN  NaN    NaN    NaN          NaN
2       Tina       Ali  36.0    F    NaN    NaN          NaN
3       jack    Milers  24.0    M    2.0    4.0          NaN
4        Amy      coov  73.0    F    3.0    4.0          NaN
5      Madhu     patil  25.0    F    4.0    4.0          NaN

In [50]:
# drop column i they only contain missing values
df.dropna(axis=1,how='all') # it will remove complete column which is null 
#df.fillna(0) # but we can not fill nan values with zero

First_name Last_name   Age  Sex  Unit1  Unit2
0      jason    Miller  42.0    M    4.0    3.0
1        NaN       NaN   NaN  NaN    NaN    NaN
2       Tina       Ali  36.0    F    NaN    NaN
3       jack    Milers  24.0    M    2.0    4.0
4        Amy      coov  73.0    F    3.0    4.0
5      Madhu     patil  25.0    F    4.0    4.0

In [51]:
# fill in missing in unit 1 with the mean value of unit 1
df["Unit1"].fillna(df["Unit1"].mean(),inplace=True)

In [52]:
# fill in missing in post TestScore  with each sex  mean values of post Test Score.
df["Unit2"].fillna(df.groupby("Sex")["Unit2"].transform("mean"),inplace=True)
df

First_name Last_name   Age  Sex  Unit1  Unit2  Final_score
0      jason    Miller  42.0    M   4.00    3.0          NaN
1        NaN       NaN   NaN  NaN   3.25    NaN          NaN
2       Tina       Ali  36.0    F   3.25    4.0          NaN
3       jack    Milers  24.0    M   2.00    4.0          NaN
4        Amy      coov  73.0    F   3.00    4.0          NaN
5      Madhu     patil  25.0    F   4.00    4.0          NaN

In [53]:
# select some rows  but ignore the missing data
df[df['Age'].notnull()& df['Sex'].notnull()]

First_name Last_name   Age Sex  Unit1  Unit2  Final_score
0      jason    Miller  42.0   M   4.00    3.0          NaN
2       Tina       Ali  36.0   F   3.25    4.0          NaN
3       jack    Milers  24.0   M   2.00    4.0          NaN
4        Amy      coov  73.0   F   3.00    4.0          NaN
5      Madhu     patil  25.0   F   4.00    4.0          NaN

In [54]:
# backfill
df.fillna(method='bfill')

# it will take back columns data.

First_name Last_name   Age Sex  Unit1  Unit2  Final_score
0      jason    Miller  42.0   M   4.00    3.0          NaN
1       Tina       Ali  36.0   F   3.25    4.0          NaN
2       Tina       Ali  36.0   F   3.25    4.0          NaN
3       jack    Milers  24.0   M   2.00    4.0          NaN
4        Amy      coov  73.0   F   3.00    4.0          NaN
5      Madhu     patil  25.0   F   4.00    4.0          NaN

In [56]:
#forward fill 
df.fillna(method='ffill',inplace=True)

In [57]:
df["Final_score"].fillna(df["Unit1"]+df["Unit2"],inplace=True)
df

First_name Last_name   Age Sex  Unit1  Unit2  Final_score
0      jason    Miller  42.0   M   4.00    3.0         7.00
1      jason    Miller  42.0   M   3.25    3.0         6.25
2       Tina       Ali  36.0   F   3.25    4.0         7.25
3       jack    Milers  24.0   M   2.00    4.0         6.00
4        Amy      coov  73.0   F   3.00    4.0         7.00
5      Madhu     patil  25.0   F   4.00    4.0         8.00

In [58]:
df["Location"]='Bengaluru'
df

First_name Last_name   Age Sex  Unit1  Unit2  Final_score   Location
0      jason    Miller  42.0   M   4.00    3.0         7.00  Bengaluru
1      jason    Miller  42.0   M   3.25    3.0         6.25  Bengaluru
2       Tina       Ali  36.0   F   3.25    4.0         7.25  Bengaluru
3       jack    Milers  24.0   M   2.00    4.0         6.00  Bengaluru
4        Amy      coov  73.0   F   3.00    4.0         7.00  Bengaluru
5      Madhu     patil  25.0   F   4.00    4.0         8.00  Bengaluru

# Hierarchical indexing

In [59]:
# create dataFrame
raw_data={
    'Company':['Google','Google','Google','Google','Facebook','Facebook','Facebook','Facebook','Amazon','Amazon','Amazon','Amazon',],
    'Project':['1st','1st','2nd','2nd','1st','1st','2nd','2nd','1st','1st','2nd','2nd',],
    'Incharge':['Sunder','Ruth','Benjamin','Sergey','Mark','Shery','Eduardo','David','Jeffrey','Andy','Keith','Edith'],
    'Sales(in millions)':[54,24,31,12,23,24,34,31,32,23,52,13],
    'Profit(in millions)':[14,8,9,4,10,11,14,13,12,7,22,4]}
df1=pd.DataFrame(raw_data,columns=['Company','Project','Incharge','Sales(in millions)','Profit(in millions)'])
df1

Company Project  Incharge  Sales(in millions)  Profit(in millions)
0     Google     1st    Sunder                  54                   14
1     Google     1st      Ruth                  24                    8
2     Google     2nd  Benjamin                  31                    9
3     Google     2nd    Sergey                  12                    4
4   Facebook     1st      Mark                  23                   10
5   Facebook     1st     Shery                  24                   11
6   Facebook     2nd   Eduardo                  34                   14
7   Facebook     2nd     David                  31                   13
8     Amazon     1st   Jeffrey                  32                   12
9     Amazon     1st      Andy                  23                    7
10    Amazon     2nd     Keith                  52                   22
11    Amazon     2nd     Edith                  13                    4

In [60]:
# set the hierarchical index but leaves the columns inplace
df1.set_index(['Company','Project'],drop=False)

Company Project  Incharge  Sales(in millions)  \
Company  Project                                                   
Google   1st        Google     1st    Sunder                  54   
         1st        Google     1st      Ruth                  24   
         2nd        Google     2nd  Benjamin                  31   
         2nd        Google     2nd    Sergey                  12   
Facebook 1st      Facebook     1st      Mark                  23   
         1st      Facebook     1st     Shery                  24   
         2nd      Facebook     2nd   Eduardo                  34   
         2nd      Facebook     2nd     David                  31   
Amazon   1st        Amazon     1st   Jeffrey                  32   
         1st        Amazon     1st      Andy                  23   
         2nd        Amazon     2nd     Keith                  52   
         2nd        Amazon     2nd     Edith                  13   

                  Profit(in millions)  
Company  Project                       
Google   1st                       14  
         1st                        8  
         2nd                        9  
         2nd                        4  
Facebook 1st                       10  
         1st                       11  
         2nd                       14  
         2nd                       13  
Amazon   1st                       12  
         1st                        7  
         2nd                       22  
         2nd                        4

In [61]:
df1.set_index(['Company','Project'],inplace=True)
df1

Incharge  Sales(in millions)  Profit(in millions)
Company  Project                                                   
Google   1st        Sunder                  54                   14
         1st          Ruth                  24                    8
         2nd      Benjamin                  31                    9
         2nd        Sergey                  12                    4
Facebook 1st          Mark                  23                   10
         1st         Shery                  24                   11
         2nd       Eduardo                  34                   14
         2nd         David                  31                   13
Amazon   1st       Jeffrey                  32                   12
         1st          Andy                  23                    7
         2nd         Keith                  52                   22
         2nd         Edith                  13                    4

# swap the level in the index

In [62]:
df1.swaplevel('Company','Project')

Incharge  Sales(in millions)  Profit(in millions)
Project Company                                                    
1st     Google      Sunder                  54                   14
        Google        Ruth                  24                    8
2nd     Google    Benjamin                  31                    9
        Google      Sergey                  12                    4
1st     Facebook      Mark                  23                   10
        Facebook     Shery                  24                   11
2nd     Facebook   Eduardo                  34                   14
        Facebook     David                  31                   13
1st     Amazon     Jeffrey                  32                   12
        Amazon        Andy                  23                    7
2nd     Amazon       Keith                  52                   22
        Amazon       Edith                  13                    4

In [63]:
# summarized the result by company
#df1.sum(level='Company') its nor working in new version
df1.groupby('Company').sum()

Incharge  Sales(in millions)  Profit(in millions)
Company                                                                    
Amazon       JeffreyAndyKeithEdith                 120                   45
Facebook     MarkSheryEduardoDavid                 112                   48
Google    SunderRuthBenjaminSergey                 121                   35

In [64]:
df1.pivot_table(index='Company', aggfunc='sum')

Incharge  Profit(in millions)  Sales(in millions)
Company                                                                    
Amazon       JeffreyAndyKeithEdith                   45                 120
Facebook     MarkSheryEduardoDavid                   48                 112
Google    SunderRuthBenjaminSergey                   35                 121

In [65]:
#finding null values
#create dataFrame
df2=pd.DataFrame({
    'Name':['Ramesh','Raghav',np.nan,np.nan],
    'Gender':[np.nan,'M','M','F'],
    'Section':['a','d','c','e'],
    'Class':[5,12,np.nan,np.nan],
    'Phone_number':[np.nan,9886409,8561729,np.nan],
    'Location':['Bengaluru','Noida','Hedrabad',np.nan],
    'email_present':['Y','N',np.nan,np.nan],
    'Door_number':[np.nan,555,345,444],
    'Street_name':['abc','def','ghi','xyz'],
    'Pin_code':[5,12,np.nan,np.nan],
    'State':[np.nan,'UP','Telangana',np.nan],
    'Dad_name':['xyz','def','ghi',np.nan]})
df2


Name Gender Section  Class  Phone_number   Location email_present  \
0  Ramesh    NaN       a    5.0           NaN  Bengaluru             Y   
1  Raghav      M       d   12.0     9886409.0      Noida             N   
2     NaN      M       c    NaN     8561729.0   Hedrabad           NaN   
3     NaN      F       e    NaN           NaN        NaN           NaN   

   Door_number Street_name  Pin_code      State Dad_name  
0          NaN         abc       5.0        NaN      xyz  
1        555.0         def      12.0         UP      def  
2        345.0         ghi       NaN  Telangana      ghi  
3        444.0         xyz       NaN        NaN      NaN

In [66]:
df2.isnull().sum()

Name             2
Gender           1
Section          0
Class            2
Phone_number     2
Location         1
email_present    2
Door_number      1
Street_name      0
Pin_code         2
State            2
Dad_name         1
dtype: int64

# Data manipulation

In [67]:
titanic_train = pd.read_csv("C:\\Users\\ww\\Data Sets\\titanic_train.csv")
titanic_train


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [68]:
#HOW TO CHECK UNIQUE VALUES OF ANY COLUMNS
titanic_train["Survived"].unique()

array([0, 1], dtype=int64)

In [69]:
# HOW TO RENAME CATEGORIES USING PANDAS
new_survived=pd.Categorical(titanic_train["Survived"])
new_servived=new_survived.rename_categories(["Died","Servived"])
new_servived.describe()

counts     freqs
categories                  
Died           549  0.616162
Servived       342  0.383838

In [70]:
titanic_train["Pclass"].unique()
# here 3 uniq values in this columns but vales is not in ordered formate

array([3, 1, 2], dtype=int64)

In [71]:
new_pclass=pd.Categorical(titanic_train["Pclass"],ordered=True)
new_pclass=new_pclass.rename_categories(["class1","class2","class3"])
new_pclass.describe()

counts     freqs
categories                  
class1         216  0.242424
class2         184  0.206510
class3         491  0.551066

In [72]:
# REASSIGN NEW NAME TO PCLASS
titanic_train["Pclass"]=new_pclass

In [73]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0  class3   
1              2         1  class1   
2              3         1  class3   
3              4         1  class1   
4              5         0  class3   
..           ...       ...     ...   
886          887         0  class2   
887          888         1  class1   
888          889         0  class3   
889          890         1  class1   
890          891         0  class3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [74]:
#convert Data to string
char_cabin=titanic_train["Cabin"].astype(str)
#list comprehensiion  creating list using another set of string, list etc
new_cabin=np.array([cabin[0] for cabin in char_cabin]) #it will take 1st later only # cabin[0] index
new_cabin=pd.Categorical(new_cabin)
new_cabin.describe()

counts     freqs
categories                  
A               15  0.016835
B               47  0.052750
C               59  0.066218
D               33  0.037037
E               32  0.035915
F               13  0.014590
G                4  0.004489
T                1  0.001122
n              687  0.771044

In [75]:
# reassign name to cabin
titanic_train["Cabin"]=new_cabin

In [76]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0  class3   
1            2         1  class1   
2            3         1  class3   
3            4         1  class1   
4            5         0  class3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     n        S  
1      0          PC 17599  71.2833     C        C  
2      0  STON/O2. 3101282   7.9250     n        S  
3      0            113803  53.1000     C        S  
4      0            373450   8.0500     n        S

#find the all pasnger whos age is missing

In [77]:
#np.where gives the index  of those missing data
missing=np.where(titanic_train["Age"].isnull()==True)
#find all the null column age missing 
missing
# it will shows the index where missing values is present

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [78]:
# using the index locate missing passangers age
titanic_train.loc[missing] # it will show only missing values
# now we can remove or we can fill null values

PassengerId  Survived  Pclass                                      Name  \
5              6         0  class3                          Moran, Mr. James   
17            18         1  class2              Williams, Mr. Charles Eugene   
19            20         1  class3                   Masselmani, Mrs. Fatima   
26            27         0  class3                   Emir, Mr. Farred Chehab   
28            29         1  class3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0  class3                          Razi, Mr. Raihed   
863          864         0  class3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0  class3               van Melkebeke, Mr. Philemon   
878          879         0  class3                        Laleff, Mr. Kristo   
888          889         0  class3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583     n        Q  
17     male  NaN      0      0      244373  13.0000     n        S  
19   female  NaN      0      0        2649   7.2250     n        C  
26     male  NaN      0      0        2631   7.2250     n        C  
28   female  NaN      0      0      330959   7.8792     n        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292     n        C  
863  female  NaN      8      2    CA. 2343  69.5500     n        S  
868    male  NaN      0      0      345777   9.5000     n        S  
878    male  NaN      0      0      349217   7.8958     n        S  
888  female  NaN      1      2  W./C. 6607  23.4500     n        S  

[177 rows x 12 columns]

# find the maximum fare

In [79]:
index=np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))
index
# here in these index present maximus fare

(array([258, 679, 737], dtype=int64),)

In [80]:
titanic_train.loc[index]

PassengerId  Survived  Pclass                                Name  \
258          259         1  class1                    Ward, Miss. Anna   
679          680         1  class1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1  class1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292     n        C  
679    male  36.0      0      1  PC 17755  512.3292     B        C  
737    male  35.0      0      0  PC 17755  512.3292     B        C

In [81]:
# finding the faming who has highest member
# siblings and parch are siblings and parents \guardeans  respectively add both of them create columns
titanic_train["Family"]=titanic_train["SibSp"]+titanic_train["Parch"]
#print(titanic_train["Family"])
most_family=np.where(titanic_train["Family"]==max(titanic_train["Family"])) # it will return the index 
titanic_train.loc[most_family]

PassengerId  Survived  Pclass                               Name     Sex  \
159          160         0  class3         Sage, Master. Thomas Henry    male   
180          181         0  class3       Sage, Miss. Constance Gladys  female   
201          202         0  class3                Sage, Mr. Frederick    male   
324          325         0  class3           Sage, Mr. George John Jr    male   
792          793         0  class3            Sage, Miss. Stella Anna  female   
846          847         0  class3           Sage, Mr. Douglas Bullen    male   
863          864         0  class3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked  Family  
159  NaN      8      2  CA. 2343  69.55     n        S      10  
180  NaN      8      2  CA. 2343  69.55     n        S      10  
201  NaN      8      2  CA. 2343  69.55     n        S      10  
324  NaN      8      2  CA. 2343  69.55     n        S      10  
792  NaN      8      2  CA. 2343  69.55     n        S      10  
846  NaN      8      2  CA. 2343  69.55     n        S      10  
863  NaN      8      2  CA. 2343  69.55     n        S      10

# Seres manipulation

In [82]:
# you can give your own index names
ser1=pd.Series(data=[1,2,3,4],index=['CA','OR','CO','AZ'])

In [83]:
ser1

CA    1
OR    2
CO    3
AZ    4
dtype: int64

In [84]:
# you can ignore writing data and index parameter pandas will understand accordingly
ser2=pd.Series([1,2,3,5],['CA','OR','NV','AZ'])

In [85]:
ser2

CA    1
OR    2
NV    3
AZ    5
dtype: int64

In [86]:
print("\n indexing by name of the iteam / object (string identifier)\n",'-'*50,sep='')
print("value for CA in ser1:",ser1['CA'])
print("value for AZ in ser1:",ser1['AZ'])
print("value for NV in ser2:",ser2['NV'])


 indexing by name of the iteam / object (string identifier)
--------------------------------------------------
value for CA in ser1: 1
value for AZ in ser1: 4
value for NV in ser2: 3


In [87]:
#you can also fetch elements by its positional index
print("\n indexing by no. (Positional value in the Series)\n",'-'*50,sep='')
print("Value for CA in ser1:",ser1[0])
print("Value for CA in ser1:",ser1[3])
print("Value for CA in ser1:",ser2[2])


 indexing by no. (Positional value in the Series)
--------------------------------------------------
Value for CA in ser1: 1
Value for CA in ser1: 4
Value for CA in ser1: 3


In [88]:
print("\n indexing by range \n",'-'*25,sep='')
print("value for OR,CO,and AZ in ser1:\n",ser1[1:4],sep='')


 indexing by range 
-------------------------
value for OR,CO,and AZ in ser1:
OR    2
CO    3
AZ    4
dtype: int64


In [89]:
ser1=pd.Series([1,2,3,4,10],['CA','OR','CO','AZ','NV'])
ser1

CA     1
OR     2
CO     3
AZ     4
NV    10
dtype: int64

In [90]:
ser2=pd.Series([1,2,5,4,30],['CA','OR','NV','PA','CO'])
ser2

CA     1
OR     2
NV     5
PA     4
CO    30
dtype: int64

In [91]:
ser3=ser1+ser2

In [92]:
print("\n After adding the two series the result will look like this...\n",'-'*50,sep='')
print(ser3)


 After adding the two series the result will look like this...
--------------------------------------------------
AZ     NaN
CA     2.0
CO    33.0
NV    15.0
OR     4.0
PA     NaN
dtype: float64


In [93]:
print("\n python tries to add values where it find common index name and keep Nan where index are missing ")


 python tries to add values where it find common index name and keep Nan where index are missing 


# DataFrame Manipulation

In [94]:
matrix_data=np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [95]:
matrix_data.dtype

dtype('int32')

In [96]:
row_label=['Raju','pandey','Srini','Sunil','Ashok']
columns_heading=['Age','Height','Weight']

In [97]:
df3=pd.DataFrame(data=matrix_data,index=row_label,columns=columns_heading)
df3

Age  Height  Weight
Raju     22      66     140
pandey   42      70     148
Srini    30      62     125
Sunil    35      68     160
Ashok    25      62     152

In [98]:
print("\n The 'Height'column \n",'-'*25,sep='')
print(df3['Height'])


 The 'Height'column 
-------------------------
Raju      66
pandey    70
Srini     62
Sunil     68
Ashok     62
Name: Height, dtype: int32


In [99]:
print("\n type of the column index by passing a list \n",'-'*55,sep='')
print(df3[['Height','Weight']])


 type of the column index by passing a list 
-------------------------------------------------------
        Height  Weight
Raju        66     140
pandey      70     148
Srini       62     125
Sunil       68     160
Ashok       62     152


In [100]:
print("\n the age column access by dot method (Not recommendation)\n",'-'*55,sep='')
print(df3.Age) # by this we can access only one column at 1 time


 the age column access by dot method (Not recommendation)
-------------------------------------------------------
Raju      22
pandey    42
Srini     30
Sunil     35
Ashok     25
Name: Age, dtype: int32


Lets understand skicing perticular elements

In [101]:
# select perticular index data using loc(index name)
df3.loc['Raju']

Age        22
Height     66
Weight    140
Name: Raju, dtype: int32

In [102]:
# select perticular index data using iloc (index possition)
df3.iloc[0]

Age        22
Height     66
Weight    140
Name: Raju, dtype: int32

In [103]:
print(df3)

        Age  Height  Weight
Raju     22      66     140
pandey   42      70     148
Srini    30      62     125
Sunil    35      68     160
Ashok    25      62     152


In [104]:
print("\n select index column for a perticular data \n")
print(df3.loc['pandey','Height'])


 select index column for a perticular data 

70


In [105]:
print("\n select index and list of the column data \n")
print(df3.loc['Ashok',['Height','Weight']])


 select index and list of the column data 

Height     62
Weight    152
Name: Ashok, dtype: int32


In [106]:
print("\n select index the column data \n")
print(df3.loc[['Srini','Sunil'],['Height','Weight']])


 select index the column data 

       Height  Weight
Srini      62     125
Sunil      68     160


# Select data on Condition

In [107]:
print("\n Rows with Height > 65 inch \n",'-'*35,sep='')
print(df3[df3['Height']>65])


 Rows with Height > 65 inch 
-----------------------------------
        Age  Height  Weight
Raju     22      66     140
pandey   42      70     148
Sunil    35      68     160


In [108]:
booldf1=df3['Height']>65
booldf2=df3['Weight']>145

In [109]:
print("\n Rows with Height > 65 inch & weight >145 lbs  \n",'-'*35,sep='')
print(df3[(booldf1)&(booldf2)])


 Rows with Height > 65 inch & weight >145 lbs  
-----------------------------------
        Age  Height  Weight
pandey   42      70     148
Sunil    35      68     160


In [110]:
print("\n after resetting index \n",'-'*35,sep='')
print(df3.reset_index()) # now remove index name


 after resetting index 
-----------------------------------
    index  Age  Height  Weight
0    Raju   22      66     140
1  pandey   42      70     148
2   Srini   30      62     125
3   Sunil   35      68     160
4   Ashok   25      62     152


In [111]:
print("\n rows with age <35 years \n",'-'*35,sep='')
df4=df3[df3['Age']<35]
print(df4)


 rows with age <35 years 
-----------------------------------
       Age  Height  Weight
Raju    22      66     140
Srini   30      62     125
Ashok   25      62     152


In [112]:
print("\n after resetting index with drop option True \n",'-'*35,sep='')
print(df3.reset_index(drop=True))


 after resetting index with drop option True 
-----------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


In [113]:
print("\n adding a new column 'Profession' \n",'-'*35,sep='')
df3['Profession']="Student Teacher Engineer Manager Accountant".split()
print(df3)


 adding a new column 'Profession' 
-----------------------------------
        Age  Height  Weight  Profession
Raju     22      66     140     Student
pandey   42      70     148     Teacher
Srini    30      62     125    Engineer
Sunil    35      68     160     Manager
Ashok    25      62     152  Accountant


In [114]:
print("\n settig 'Profession' columns index \n",'-'*35,sep='')
print(df3.set_index('Profession'))


 settig 'Profession' columns index 
-----------------------------------
            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Manager      35      68     160
Accountant   25      62     152


In [136]:
# finding null values

In [137]:
#create dataFrame
df2=pd.DataFrame({
    'Name':['Ramesh','Raghav',np.nan,np.nan],
    'Gender':[np.nan,'M','M','F'],
    'Section':['a','d','c','e'],
    'Class':[5,12,np.nan,np.nan],
    'Phone_number':[np.nan,9886409,8561729,np.nan],
    'Location':['Bengaluru','Noida','Hedrabad',np.nan],
    'email_present':['Y','N',np.nan,np.nan],
    'Door_number':[np.nan,555,345,444],
    'Street_name':['abc','def','ghi','xyz'],
    'Pin_code':[5,12,np.nan,np.nan],
    'State':[np.nan,'UP','Telangana',np.nan],
    'Dad_name':['xyz','def','ghi',np.nan]})
df2

Name Gender Section  Class  Phone_number   Location email_present  \
0  Ramesh    NaN       a    5.0           NaN  Bengaluru             Y   
1  Raghav      M       d   12.0     9886409.0      Noida             N   
2     NaN      M       c    NaN     8561729.0   Hedrabad           NaN   
3     NaN      F       e    NaN           NaN        NaN           NaN   

   Door_number Street_name  Pin_code      State Dad_name  
0          NaN         abc       5.0        NaN      xyz  
1        555.0         def      12.0         UP      def  
2        345.0         ghi       NaN  Telangana      ghi  
3        444.0         xyz       NaN        NaN      NaN

In [138]:
df2.isnull().sum()

Name             2
Gender           1
Section          0
Class            2
Phone_number     2
Location         1
email_present    2
Door_number      1
Street_name      0
Pin_code         2
State            2
Dad_name         1
dtype: int64