# Numpy arrays

In [4]:
import numpy as np
import random
from random import randint as ri

In [2]:
#ccreating array
a=np.array([5,9,13])
print(a)
print(type([5,9,13]))

[ 5  9 13]
<class 'list'>


In [3]:
#convert list into array
b=([1,2,3,4,5,6,7,8,9,10,2,3,4,5,6])
print(b)
print("type-",type(b))
#print("data Type-",bb.dtype) # its shown error because its not array its list 
#now convert into array
b1=np.array(b)
print("B1",b1)
print("array dType-",b1.dtype)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6]
type- <class 'list'>
B1 [ 1  2  3  4  5  6  7  8  9 10  2  3  4  5  6]
array dType- int32


In [4]:
#two dimention arrays
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Type-",c.dtype)
print('\n',c)
print(type(c))

Type- int32

 [[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [5]:
#data type conversion
d=np.array([1,2,3],dtype=float)
d

array([1., 2., 3.])

In [6]:
e=np.array(b,dtype=float)
e

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  2.,  3.,  4.,
        5.,  6.])

# creating array using matrix mat
it mean we can create array with multiple rows and columns by using np.mat function

In [7]:
f= np.array(np.mat('123;345'))
print(f.dtype)
print(type(f))
print(f)

int32
<class 'numpy.ndarray'>
[[123]
 [345]]


In [8]:
#copy array into others use asarray
g=np.asarray(a)
g

array([ 5,  9, 13])

In [9]:
my_mat=([[1,2,3],[4,5,6],[8,7,5]])
print(my_mat)
mat=np.array(my_mat)
print("Type/Class of this Object:",type(mat))

[[1, 2, 3], [4, 5, 6], [8, 7, 5]]
Type/Class of this Object: <class 'numpy.ndarray'>


In [10]:
print("Here is the matrix \n------\n",mat,"\n------")
# checxk dimention with ndim funtion
print("Dimention of this matrix:",mat.ndim,sep=" ")
# check size with size function its give total no. Elements
print("Size of matrix:",mat.size,sep=" ")
#WE can check shape also its tell rows and columns
print("Shape of Mtrix:",mat.shape)
print("datatype of matrix:",mat.dtype)

Here is the matrix 
------
 [[1 2 3]
 [4 5 6]
 [8 7 5]] 
------
Dimention of this matrix: 2
Size of matrix: 9
Shape of Mtrix: (3, 3)
datatype of matrix: int32


# Numpy array Linspace arange(), reverse

In [11]:
# dont work with python range 
list(range(2,10.5,.4)) # it shown error
#range(start,end,step size|gap)

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
# but we can create range list in numpy array with a range function
h=np.arange(2,10.5,.4) # start with 2,end with 10.5,gap is .4
h

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [13]:
# We can perform Reverse Order also
h[: :-1] # [start : end : step size -1 ] # start empty it mean start with 0 

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [14]:
h[:10:-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4])

In [15]:
print("every 5th number from 50 in reverse order \n",np.arange(50,0,-5))

every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5]


In [16]:
print("every 5th number from 50 in reverse order \n",np.arange(0,50,-5)) 
# it will not give output because in start will give end ping in end point we will give start point


every 5th number from 50 in reverse order 
 []


# linspace function (it mean we want 5 element b\w 10 to 40 or these 5 element should we equal


In [17]:
# np.linspace tell no of elemts
print("linearly spaced no. b\w 1 and 5\n--",np.linspace(10,40,5,retstep=True)) #linspace(start,end,no.of element)

linearly spaced no. b\w 1 and 5
-- (array([10. , 17.5, 25. , 32.5, 40. ]), 7.5)


In [18]:
lin=np.linspace(10,40,10,retstep=True) 
lin

(array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
        26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ]),
 3.3333333333333335)

In [19]:
# now check space between the points
lin=np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)
#(2.0 start,3.0 end,i want 4 elemnt,if u want print endpoint then its True otherwise Flase,retstep it tel distand or gap between points)
lin

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [20]:
print(np.linspace(4.5678,25.9865,39,retstep=True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), 0.56365)


# 4rth Vedio

# Matrix Creation

In [21]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


matrix of columns

In [22]:
print(np.zeros((5,6))) # matrix create 5 raws and 6 columns


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
print(np.ones((5,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
#if we want create matrix any perticular no then write like this
print(5*np.ones((2,3)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [25]:
print(7*np.ones((6,5)))

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [26]:
#construct diagonal matrix
x=np.arange(0,30).reshape(3,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Random function

In [27]:
print("Random no.generation (from uniform distribution )") # uniform means data is similar distrubition almost
print(np.random.rand(10,6)) # we will get all are +ve data

Random no.generation (from uniform distribution )
[[0.38445583 0.70571308 0.20037566 0.1875061  0.64927599 0.23530329]
 [0.36150054 0.40548445 0.38964075 0.76968201 0.76802794 0.46996243]
 [0.42345555 0.85332692 0.28827589 0.6593647  0.43415469 0.39510397]
 [0.60073147 0.89525109 0.09509514 0.6596233  0.11039586 0.34293155]
 [0.26869093 0.76011412 0.63747969 0.92242812 0.70769819 0.59215666]
 [0.2892474  0.57805777 0.35996581 0.94107898 0.13641787 0.62714355]
 [0.96682879 0.41931255 0.7852063  0.78079871 0.18461454 0.20747335]
 [0.85450812 0.77707142 0.59256881 0.0346831  0.19070031 0.69387079]
 [0.76734498 0.63187838 0.2675665  0.47755375 0.18029349 0.67692245]
 [0.23883562 0.82310269 0.07465294 0.75931866 0.75259192 0.52988593]]


In [28]:
np.random.seed(5) # it means it will fix the value
print(np.random.rand(10,6))

[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]


# Randn function
#it will generate +ve or -Ve number from normal distribution with Zero mean ns std = 1

In [29]:
print(np.random.randn(10,6))

[[ 1.13934298  0.4944404  -0.33633626 -0.10061435  1.41339802  0.22125412]
 [-1.31077313 -0.68956523 -0.57751323  1.15220477 -0.10716398  2.26010677]
 [ 0.65661947  0.12480683 -0.43570392  0.97217931 -0.24071114 -0.82412345]
 [ 0.56813272  0.01275832  1.18906073 -0.07359332 -2.85968797  0.7893664 ]
 [-1.87774088  1.53875615  1.82136474 -0.42703139 -1.16470191 -1.39707402]
 [ 0.87265462 -0.20211818 -0.59835993 -0.2434197   2.08851469  0.34691933]
 [ 0.74572695  0.77690759  1.01842113  1.06135144 -0.71046645 -0.2151878 ]
 [-0.76076031 -0.71116323  1.14150774 -0.50175555 -0.07915136 -0.69282634]
 [-0.59340277  0.78823794 -0.44542999 -0.48212019  0.49355766  0.50048733]
 [ 0.79242262  0.17076445 -1.75374086  0.63029648  0.49832921  1.01813761]]


# Randint function


In [30]:
print("Random Integer Vector",np.random.randint(5,20,10)) #start, end ,no. of elementsS

Random Integer Vector [ 8 12  8 12  8  7 11 18 11  7]


In [31]:
print("random integer Matrix")
print(np.random.randint(1,30,(6,7)))

random integer Matrix
[[16  8  1  4 29 24  6]
 [ 2 28  7 28  8  4 15]
 [10  8 26 27  8 23  7]
 [15  5 11 22 11  5  1]
 [17 18 29  6  4 16 18]
 [24 17 12 27 26  9 20]]


# Numpy Conditions

In [37]:
np.random.seed(5)
a=np.random.randint(1,40,10)
a

array([36, 15, 39, 17, 10,  9, 37, 28, 31, 17])

In [44]:
# replace data with fixed number
np.clip(a,a_min=10,a_max=25)

array([25, 15, 25, 17, 10, 10, 25, 25, 25, 17])

In [45]:
#it gives index detail also
print(np.where(a<10))

(array([5], dtype=int64),)


In [46]:
print(np.where(a<16))

(array([1, 4, 5], dtype=int64),)


In [47]:
print(np.where(a==36))

(array([0], dtype=int64),)


# Reshape Sort

In [10]:
import numpy
from numpy import random
from numpy.random import randint as ri

In [51]:
j=ri(1,99,30)
j

array([32,  3, 69, 39, 84, 20, 19,  8, 31, 63, 12, 68, 66, 56,  4, 92, 79,
       28, 30, 34, 90, 86,  8, 17, 95, 15, 91, 32, 10, 39])

In [52]:
#We can create matrix from j or we can do reshape also
k=j.reshape(2,3,5) # it mena 2 matrix create in j 3 raws and 5 columns
k

array([[[32,  3, 69, 39, 84],
        [20, 19,  8, 31, 63],
        [12, 68, 66, 56,  4]],

       [[92, 79, 28, 30, 34],
        [90, 86,  8, 17, 95],
        [15, 91, 32, 10, 39]]])

In [53]:
l=j.reshape(6,5)
l

array([[32,  3, 69, 39, 84],
       [20, 19,  8, 31, 63],
       [12, 68, 66, 56,  4],
       [92, 79, 28, 30, 34],
       [90, 86,  8, 17, 95],
       [15, 91, 32, 10, 39]])

In [57]:
print("min of j:",j.min())
print("max of j:",j.max())

min of j: 3
max of j: 95


# sorting

In [59]:
m=ri(1,100,25).reshape(5,5)
m

array([[38, 95, 76,  6, 23],
       [53, 70, 83, 61, 92],
       [30, 89, 98, 93, 80],
       [71, 36, 21, 50, 73],
       [33, 83, 14, 93, 19]])

In [66]:
print("\n 5*5 matrix of random integers \n",'-'*50,"\n",m)


 5*5 matrix of random integers 
 -------------------------------------------------- 
 [[38 95 76  6 23]
 [53 70 83 61 92]
 [30 89 98 93 80]
 [71 36 21 50 73]
 [33 83 14 93 19]]


# print("\n here is the sorted matrix along each raw \n",'-'*50,"\n",np.sort(m)) # axis = 1 by default 

In [68]:
print("\n here is the sorted matrix along each raw \n",'-'*50,"\n",np.sort(m,axis=0))


 here is the sorted matrix along each raw 
 -------------------------------------------------- 
 [[30 36 14  6 19]
 [33 70 21 50 23]
 [38 83 76 61 73]
 [53 89 83 93 80]
 [71 95 98 93 92]]


# 8th vedio

# Indexing sort Update

In [70]:
arr=np.arange(13,30)
print('Array',arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [71]:
#show 7th Index
print("element at 7th index is:",arr[7])

element at 7th index is: 20


In [77]:
print(arr[3:6]) # start index end index

[16 17 18]


In [78]:
print(arr[4:]) # start index Lst index

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [80]:
print("element from last backwards are :",arr[-1: :-2]) #-1 start  end everything step size , -1 very last element

element from last backwards are : [29 27 25 23 21 19 17 15 13]


In [83]:
print("7 element from last backwards are :",arr[-1:-8:-1])

7 element from last backwards are : [29 28 27 26 25 24 23]


In [84]:
arr2=np.arange(0,21,2)
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
print("element at 2nd 4th and 9th index are :",arr2[[2,4,9]]) #create a list as the index

element at 2nd 4th and 9th index are : [ 4  8 18]


In [86]:
#create matrix
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
print ("\n doubel bracket index \n ---------------" )
print("element in raw index  1 and column index 2 :",mat[1][2])


 doubel bracket index 
 ---------------
element in raw index  1 and column index 2 : 6


In [88]:
print("entire raw at index 2:",mat[2])

entire raw at index 2: [7 8 9]


In [93]:
print("entire colum at index 3:\n",mat[:,1:])

entire colum at index 3:
 [[2 3]
 [5 6]
 [8 9]]


In [95]:
mat[:,2:]

array([[3],
       [6],
       [9]])

In [97]:
print("matrix with raw index 1 and 2 and column index 3 and 4 : \n",mat[1:2,1:2]) #last index will be exclusive

matrix with raw index 1 and 2 and column index 3 and 4 : 
 [[5]]


In [98]:
print(mat[0:2,[1,2]]) # 0:2 range of colum , [1,2] its selective columns

[[2 3]
 [5 6]]


# update matrix

In [99]:
print("original Matrix\n\n",mat)

original Matrix

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
# i want update this matrix
mat[0,1]=35 # 0 raw column 1
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [102]:
mat[1,0]=100 # 1 raw 0 column
mat

array([[  1,  35,   3],
       [100,   5,   6],
       [  7,   8,   9]])

# Subsetting

In [12]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2 - digit number \n--------------------------------------\n",mat)

Matrix of random 2 - digit number 
--------------------------------------
 [[82 93 97 65 87]
 [19 82 56 53 51]
 [97 45 12 26 59]]


In [13]:
xyz=mat[mat>70]
xyz

array([82, 93, 97, 87, 82, 97])

In [14]:
print("elements which is Grater than 50 \n",mat[mat>50])

elements which is Grater than 50 
 [82 93 97 65 87 82 56 53 51 97 59]


In [15]:
#if we write this code then it will give output in True False
mat>50

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False, False, False,  True]])

In [16]:
print(np.where(mat==55)) # here no num. ==55

(array([], dtype=int64), array([], dtype=int64))


In [18]:
print(np.where(mat==65))

(array([0], dtype=int64), array([3], dtype=int64))


# Universal Function

In [27]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n 1st matrix of random single Digit number \n---------------------\n",mat1)
print("\n 2nd matrix of random single Digit number \n---------------------\n",mat2)


 1st matrix of random single Digit number 
---------------------
 [[3 8 9]
 [6 8 3]
 [4 7 1]]

 2nd matrix of random single Digit number 
---------------------
 [[7 5 1]
 [4 7 7]
 [4 6 2]]


In [28]:
print("\n Addition \n----------------\n",mat1+mat2)
print("\n Multuplication \n----------------\n",mat1*mat2)
# it will addition index wise


 Addition 
----------------
 [[10 13 10]
 [10 15 10]
 [ 8 13  3]]

 Multuplication 
----------------
 [[21 40  9]
 [24 56 21]
 [16 42  2]]


In [30]:
#print again matrix
print("mat 1=\n",mat1)
print("mat 2=\n",mat2)

mat 1=
 [[3 8 9]
 [6 8 3]
 [4 7 1]]
mat 2=
 [[7 5 1]
 [4 7 7]
 [4 6 2]]


In [31]:
print("\n Division \n----------------\n",mat1/mat2)
print("\n linear combination 3*A - 2*B \n----------------\n",3*mat1-2*mat2)


 Division 
----------------
 [[0.42857143 1.6        9.        ]
 [1.5        1.14285714 0.42857143]
 [1.         1.16666667 0.5       ]]

 linear combination 3*A - 2*B 
----------------
 [[-5 14 25]
 [10 10 -5]
 [ 4  9 -1]]


# Broadcasting

In [33]:
start=np.zeros((3,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# create a rank 1 ndarray with 3 values
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [35]:
# add each row of start using broadcasting
y=start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [36]:
# its create vertically 
new_row=add_rows.T
print(new_row)

[[1]
 [0]
 [2]]


In [37]:
#again horizontally
test=new_row+start
test

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

In [38]:
# create an ndarray which is 4*1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


# Array math

In [39]:
mat3=np.array(ri(1,10,9)).reshape(3,3)
mat4=np.array(ri(1,10,9)).reshape(3,3)
print("\n 1st matrix of random single Digit number \n---------------------\n",mat3)
print("\n 2nd matrix of random single Digit number \n---------------------\n",mat4)


 1st matrix of random single Digit number 
---------------------
 [[9 7 5]
 [8 7 8]
 [4 8 6]]

 2nd matrix of random single Digit number 
---------------------
 [[3 4 2]
 [1 6 5]
 [1 4 2]]


In [40]:
# create sq-root of mat3 
print("\n sq-root \n----------------\n",np.sqrt(mat3))


 sq-root 
----------------
 [[3.         2.64575131 2.23606798]
 [2.82842712 2.64575131 2.82842712]
 [2.         2.82842712 2.44948974]]


In [41]:
# create square of mat3 
print("\n sq-root \n----------------\n",np.square(mat3))


 sq-root 
----------------
 [[81 49 25]
 [64 49 64]
 [16 64 36]]


# Similarly we can apply more function on this 

In [42]:
import numpy
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [43]:
a=np.array([1,2,3],dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [44]:
a=np.array([1,2,3,5,8])
a=a+1
print(a[1])

3


In [45]:
a=np.array([1,2,3])
a

array([1, 2, 3])